import { Router } from 'express';
import { deleteDMMessage, editDMMessage, getDMMessages, listDMs, sendDMMessage, startDM } from '../controllers/dm.js';
import { requireAuth } from '../middleware/auth.js';
const router = Router();
router.use(requireAuth);
router.get('/', listDMs);
router.post('/', startDM);
router.get('/:dmId', getDMMessages);
router.post('/:dmId', sendDMMessage);
router.put('/:dmId/:messageId', editDMMessage);
router.delete('/:dmId/:messageId', deleteDMMessage);
export default router;
